# Generated by Django 5.1.15 on 2026-08-02 16:10

import apps.offers.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inquiries', '0003_alter_inquiry_status_and_more'),
        ('teams', '0002_alter_teaminvitation_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(db_index=True, default=apps.offers.models.generate_uid, editable=False, max_length=12, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('artist_name', models.CharField(max_length=128)),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=128)),
                ('venue_address', models.CharField(max_length=256)),
                ('city_state_country_zip', models.CharField(max_length=128)),
                ('venue_phone', models.CharField(max_length=32)),
                ('offer_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_attendance', models.IntegerField()),
                ('past_performers', models.CharField(blank=True, max_length=256, null=True)),
                ('social_media_request', models.CharField(blank=True, max_length=256, null=True)),
                ('what_is_event_for', models.CharField(blank=True, max_length=256, null=True)),
                ('other_artists', models.CharField(blank=True, max_length=256, null=True)),
                ('contact_signatory_name', models.CharField(max_length=128)),
                ('contact_signatory_address', models.CharField(max_length=256)),
                ('contact_signatory_contact_info', models.CharField(max_length=32)),
                ('contact_buyer_name', models.CharField(max_length=128)),
                ('contact_buyer_address', models.CharField(max_length=256)),
                ('contact_buyer_contact_info', models.CharField(max_length=32)),
                ('contact_production_name', models.CharField(max_length=128)),
                ('contact_production_contact_info', models.CharField(max_length=32)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('inquiry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='inquiries.inquiry')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_deal_offers', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_deal_offers', to=settings.AUTH_USER_MODEL)),
                ('shared_with_teams', models.ManyToManyField(blank=True, related_name='shared_offers', to='teams.team')),
                ('shared_with_users', models.ManyToManyField(blank=True, related_name='shared_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'offers',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OfferDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.FileField(upload_to='offers/documents/')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='offers.offer')),
            ],
            options={
                'db_table': 'offer_documents',
            },
        ),
        migrations.CreateModel(
            name='OfferSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signature', models.ImageField(upload_to='offers/signatures/')),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='offers.offer')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'offer_signatures',
                'ordering': ('signed_at',),
            },
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['sender', '-created_at'], name='offers_sender__00b623_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['receiver', '-created_at'], name='offers_receive_9b5d77_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['receiver', 'status', '-created_at'], name='offers_receive_2cfaf5_idx'),
        ),
        migrations.AddConstraint(
            model_name='offersignature',
            constraint=models.UniqueConstraint(fields=('offer', 'signer'), name='uniq_offer_signer'),
        ),
    ]
