# Generated by Django 5.1.15 on 2026-08-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_offer_airfare_offer_backline_offer_catering_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='included_facilities',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
