# Generated by Django 5.1.15 on 2026-08-04 16:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0004_inquiry_venue_name'),
        ('offers', '0003_offer_included_facilities'),
        ('teams', '0002_alter_teaminvitation_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['date'], name='offers_date_0bb55b_idx'),
        ),
    ]
