# Generated by Django 5.1.15 on 2026-06-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_last_seen_at_user_phone_notificationpreferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('artist', 'Artist'), ('agent', 'Agent'), ('talent-buyer', 'Talent Buyer'), ('venue', 'Venue'), ('organizer', 'Organizer')], max_length=32),
        ),
    ]
