# Generated by Django 5.1.15 on 2026-09-20 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        ('teams', '0005_add_supervisor_mini_super_admin_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='team',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_conversation', to='teams.team'),
        ),
    ]
