# Generated by Django 5.1.15 on 2026-09-20 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_add_team_group_conversation'),
        ('offers', '0004_offer_offers_date_0bb55b_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='kind',
            field=models.CharField(choices=[('text', 'Text'), ('offer', 'Offer')], default='text', max_length=8),
        ),
        migrations.AddField(
            model_name='message',
            name='offer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_message', to='offers.offer'),
        ),
    ]
