# Generated by Django 5.1.15 on 2026-09-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_add_offer_kind_to_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='system_event',
            field=models.JSONField(blank=True, help_text="Set only for kind=system: {'event': 'member_added'|'member_removed'|'member_left', 'actor': {...}, 'target': {...}}. Actor/target are name/email snapshots taken at event time, not live user references - a later rename shouldn't rewrite history.", null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='kind',
            field=models.CharField(choices=[('text', 'Text'), ('offer', 'Offer'), ('system', 'System')], default='text', max_length=8),
        ),
    ]
