# Generated by Django 5.1.15 on 2026-09-29 08:43

import apps.messaging.crypto
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_add_system_message_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=apps.messaging.crypto.EncryptedTextField(blank=True),
        ),
    ]
