# Generated by Django 5.1.15 on 2026-08-01 13:48

import apps.inquiries.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(db_index=True, default=apps.inquiries.models.generate_uid, editable=False, max_length=12, unique=True)),
                ('receiver_email', models.EmailField(max_length=254)),
                ('event_title', models.CharField(max_length=128)),
                ('start_date_time', models.DateTimeField()),
                ('expected_attendance', models.PositiveIntegerField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('full_name', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_inquiries', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_inquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inquiries',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['sender', '-created_at'], name='inquiries_sender__68ca14_idx'), models.Index(fields=['receiver', '-created_at'], name='inquiries_receive_773024_idx')],
            },
        ),
    ]
