# Generated by Django 5.1.15 on 2026-08-01 13:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0002_inquiry_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='inquiry',
            index=models.Index(fields=['receiver', 'status', '-created_at'], name='inquiries_receive_2be019_idx'),
        ),
    ]
