# Generated by Django 5.1.15 on 2026-08-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0003_alter_inquiry_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='venue_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
