# Generated by Django 5.1.15 on 2026-09-21 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seatgeek', '0002_event_date_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency_roster_url', models.URLField(help_text="Link to the agency/management's public roster page listing this artist.", max_length=500)),
                ('confirmation_email', models.EmailField(help_text='Email address the artist confirmed representation from.', max_length=254)),
                ('company_agency', models.CharField(blank=True, help_text='Company or agency name of the claimant (optional).', max_length=255)),
                ('business_email', models.EmailField(help_text='Work/business email of the claimant.', max_length=254)),
                ('adder_role', models.CharField(help_text="Claimant's role at their company (e.g. Booking Agent, Manager).", max_length=255)),
                ('representation', models.TextField(help_text='Free-text description of the representation arrangement.')),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('artist_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artist_claims_received', to=settings.AUTH_USER_MODEL)),
                ('claimant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_claims_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artist_claims_reviewed', to=settings.AUTH_USER_MODEL)),
                ('seatgeek_performer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='seatgeek.performers')),
            ],
            options={
                'db_table': 'artist_claims',
            },
        ),
        migrations.CreateModel(
            name='ArtistClaimDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='artist_claims/documents/')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='artist_claims.artistclaim')),
            ],
            options={
                'db_table': 'artist_claim_documents',
            },
        ),
        migrations.AddIndex(
            model_name='artistclaim',
            index=models.Index(fields=['artist_user', 'status'], name='artist_clai_artist__b026c3_idx'),
        ),
        migrations.AddIndex(
            model_name='artistclaim',
            index=models.Index(fields=['seatgeek_performer', 'status'], name='artist_clai_seatgee_956e96_idx'),
        ),
        migrations.AddIndex(
            model_name='artistclaim',
            index=models.Index(fields=['claimant', 'status'], name='artist_clai_claiman_7a9412_idx'),
        ),
        migrations.AddConstraint(
            model_name='artistclaim',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('artist_user__isnull', False), ('seatgeek_performer__isnull', True)), models.Q(('artist_user__isnull', True), ('seatgeek_performer__isnull', False)), _connector='OR'), name='artist_claim_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='artistclaim',
            constraint=models.UniqueConstraint(condition=models.Q(('artist_user__isnull', False), models.Q(('status', 'rejected'), _negated=True)), fields=('claimant', 'artist_user'), name='uniq_live_claimant_artist_user'),
        ),
        migrations.AddConstraint(
            model_name='artistclaim',
            constraint=models.UniqueConstraint(condition=models.Q(('seatgeek_performer__isnull', False), models.Q(('status', 'rejected'), _negated=True)), fields=('claimant', 'seatgeek_performer'), name='uniq_live_claimant_sg_performer'),
        ),
    ]
