# Generated by Django 5.1.15 on 2026-05-13 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventDownloaderProgresses',
            fields=[
                ('id', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('pages_processed', models.IntegerField()),
                ('pages', models.IntegerField()),
                ('page_size', models.IntegerField()),
                ('provider_name', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'event_downloader_progresses',
            },
        ),
        migrations.CreateModel(
            name='PerformerScorerProgresses',
            fields=[
                ('id', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('last_processed_performer_id', models.CharField(max_length=256)),
                ('completed', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'performer_scorer_progresses',
            },
        ),
        migrations.CreateModel(
            name='SeatgeekGenres',
            fields=[
                ('id', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('seatgeek_id', models.CharField(max_length=256, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('slug', models.CharField(max_length=256)),
                ('image', models.CharField(blank=True, max_length=256, null=True)),
                ('primary', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'seatgeek_genres',
            },
        ),
        migrations.CreateModel(
            name='Performers',
            fields=[
                ('id', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('provider_id', models.CharField(max_length=256)),
                ('provider_name', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=256)),
                ('image', models.CharField(max_length=256)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'performers',
                'unique_together': {('provider_name', 'provider_id')},
            },
        ),
        migrations.CreateModel(
            name='Venues',
            fields=[
                ('id', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('provider_name', models.CharField(max_length=256)),
                ('provider_id', models.CharField(max_length=256)),
                ('provider_slug', models.CharField(max_length=256)),
                ('provider_url', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=256)),
                ('state', models.CharField(max_length=256)),
                ('postal_code', models.CharField(max_length=256)),
                ('country', models.CharField(max_length=256)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('capacity', models.IntegerField()),
                ('score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'venues',
                'unique_together': {('provider_name', 'provider_id')},
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('provider_name', models.CharField(max_length=256)),
                ('provider_id', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=256)),
                ('location_name', models.CharField(max_length=256)),
                ('location_url', models.CharField(max_length=256)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('address', models.CharField(max_length=256)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('long', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='seatgeek.venues')),
            ],
            options={
                'db_table': 'events',
                'unique_together': {('provider_name', 'provider_id')},
            },
        ),
        migrations.CreateModel(
            name='PerformerGenres',
            fields=[
                ('id', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('genre', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seatgeek.performers')),
            ],
            options={
                'db_table': 'performer_genres',
                'unique_together': {('performer', 'genre')},
            },
        ),
        migrations.CreateModel(
            name='PerformerEvents',
            fields=[
                ('id', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seatgeek.events')),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seatgeek.performers')),
            ],
            options={
                'db_table': 'performer_events',
                'unique_together': {('performer', 'event')},
            },
        ),
        migrations.CreateModel(
            name='PerformerSeatgeekGenres',
            fields=[
                ('id', models.CharField(max_length=191, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seatgeek.performers')),
                ('seatgeek_genre', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='seatgeek.seatgeekgenres')),
            ],
            options={
                'db_table': 'performer_seatgeek_genres',
                'unique_together': {('performer', 'seatgeek_genre')},
            },
        ),
    ]
