# Generated by Django 5.1.15 on 2026-07-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(choices=[('privacy-policy', 'Privacy Policy'), ('terms-of-service', 'Terms of Service'), ('cookie-policy', 'Cookie Policy'), ('about-us', 'About Us')], max_length=32, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'static_pages',
                'ordering': ('slug',),
            },
        ),
    ]
