# Generated by Django 5.1.15 on 2026-07-16 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(choices=[('artist', 'Artist'), ('venue', 'Venue')], max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_teams', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teams',
            },
        ),
        migrations.CreateModel(
            name='TeamInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('artist', 'Artist'), ('manager', 'Manager'), ('business_manager', 'Business Manager'), ('responsible_agent', 'Responsible Agent'), ('segment_agent', 'Segment Agent'), ('tour_manager', 'Tour Manager'), ('legal_representative', 'Legal Representative'), ('ceo_gm', 'CEO / GM'), ('entertainment_manager', 'Entertainment Manager'), ('talent_buyer', 'Talent Buyer'), ('production_director', 'Production Director'), ('marketing_director', 'Marketing Director'), ('finance_team', 'Finance Team'), ('legal_team', 'Legal Team')], max_length=32)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Awaiting Acceptance'), ('accepted', 'Accepted'), ('revoked', 'Revoked')], default='pending', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_invitations_accepted', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='teams.team')),
            ],
            options={
                'db_table': 'team_invitations',
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('artist', 'Artist'), ('manager', 'Manager'), ('business_manager', 'Business Manager'), ('responsible_agent', 'Responsible Agent'), ('segment_agent', 'Segment Agent'), ('tour_manager', 'Tour Manager'), ('legal_representative', 'Legal Representative'), ('ceo_gm', 'CEO / GM'), ('entertainment_manager', 'Entertainment Manager'), ('talent_buyer', 'Talent Buyer'), ('production_director', 'Production Director'), ('marketing_director', 'Marketing Director'), ('finance_team', 'Finance Team'), ('legal_team', 'Legal Team')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_memberships_approved', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_memberships_invited', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='teams.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'team_memberships',
            },
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['domain', 'status'], name='teams_domain_235ffa_idx'),
        ),
        migrations.AddIndex(
            model_name='team',
            index=models.Index(fields=['created_by', 'status'], name='teams_created_7f2d3d_idx'),
        ),
        migrations.AddIndex(
            model_name='teaminvitation',
            index=models.Index(fields=['team', 'status'], name='team_invita_team_id_d0b794_idx'),
        ),
        migrations.AddIndex(
            model_name='teaminvitation',
            index=models.Index(fields=['email', 'status'], name='team_invita_email_f39c53_idx'),
        ),
        migrations.AddConstraint(
            model_name='teaminvitation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('team', 'email', 'role'), name='uniq_live_team_invitation'),
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['team', 'status'], name='team_member_team_id_807061_idx'),
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['user', 'status'], name='team_member_user_id_aa7ff1_idx'),
        ),
        migrations.AddConstraint(
            model_name='teammembership',
            constraint=models.UniqueConstraint(fields=('team', 'user'), name='uniq_team_user'),
        ),
    ]
