# Generated by Django 5.1.15 on 2026-08-18 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_teaminvitation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistRepresentationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency_roster_url', models.URLField(help_text="Link to the agency/management's public roster page listing this artist.", max_length=500)),
                ('confirmation_email', models.EmailField(help_text='Email address the artist confirmed representation from.', max_length=254)),
                ('company_agency', models.CharField(blank=True, help_text='Company or agency name of the person adding the artist (optional).', max_length=255)),
                ('business_email', models.EmailField(help_text='Work/business email of the person adding the artist.', max_length=254)),
                ('adder_role', models.CharField(help_text='Role of the person adding the artist at their company (e.g. Booking Agent, Manager).', max_length=255)),
                ('representation', models.TextField(help_text='Free-text description of the representation arrangement.')),
                ('note', models.TextField(blank=True)),
                ('invitation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artist_representation_details', to='teams.teaminvitation')),
                ('membership', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artist_representation_details', to='teams.teammembership')),
            ],
            options={
                'db_table': 'team_artist_representation_details',
            },
        ),
        migrations.CreateModel(
            name='ArtistRepresentationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='teams/artist_representation/')),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='teams.artistrepresentationdetails')),
            ],
            options={
                'db_table': 'team_artist_representation_documents',
            },
        ),
        migrations.AddConstraint(
            model_name='artistrepresentationdetails',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('invitation__isnull', True), ('membership__isnull', False)), models.Q(('invitation__isnull', False), ('membership__isnull', True)), _connector='OR'), name='artist_repr_details_exactly_one_parent'),
        ),
    ]
