# Generated by Django 5.1.15 on 2026-08-19 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_add_adder_fields_to_artist_representation_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='teams/documents/')),
                ('invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='teams.teaminvitation')),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='teams.teammembership')),
            ],
            options={
                'db_table': 'team_membership_documents',
            },
        ),
        migrations.DeleteModel(
            name='ArtistRepresentationDocument',
        ),
        migrations.AddConstraint(
            model_name='membershipdocument',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('invitation__isnull', True), ('membership__isnull', False)), models.Q(('invitation__isnull', False), ('membership__isnull', True)), _connector='OR'), name='membership_doc_exactly_one_parent'),
        ),
    ]
