# Generated by Django 5.1.15 on 2026-09-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_membershipdocument_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminvitation',
            name='role',
            field=models.CharField(choices=[('artist', 'Artist'), ('manager', 'Manager'), ('business_manager', 'Business Manager'), ('responsible_agent', 'Responsible Agent'), ('segment_agent', 'Segment Agent'), ('tour_manager', 'Tour Manager'), ('legal_representative', 'Legal Representative'), ('artist_supervisor', 'Supervisor'), ('artist_mini_super_admin', 'Mini Super Admin'), ('ceo_gm', 'CEO / GM'), ('entertainment_manager', 'Entertainment Manager'), ('talent_buyer', 'Talent Buyer'), ('production_director', 'Production Director'), ('marketing_director', 'Marketing Director'), ('finance_team', 'Finance Team'), ('legal_team', 'Legal Team'), ('venue_supervisor', 'Supervisor'), ('venue_mini_super_admin', 'Mini Super Admin')], max_length=32),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='role',
            field=models.CharField(choices=[('artist', 'Artist'), ('manager', 'Manager'), ('business_manager', 'Business Manager'), ('responsible_agent', 'Responsible Agent'), ('segment_agent', 'Segment Agent'), ('tour_manager', 'Tour Manager'), ('legal_representative', 'Legal Representative'), ('artist_supervisor', 'Supervisor'), ('artist_mini_super_admin', 'Mini Super Admin'), ('ceo_gm', 'CEO / GM'), ('entertainment_manager', 'Entertainment Manager'), ('talent_buyer', 'Talent Buyer'), ('production_director', 'Production Director'), ('marketing_director', 'Marketing Director'), ('finance_team', 'Finance Team'), ('legal_team', 'Legal Team'), ('venue_supervisor', 'Supervisor'), ('venue_mini_super_admin', 'Mini Super Admin')], max_length=32),
        ),
    ]
