# Generated by Django 5.1.15 on 2026-05-06 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verb', models.CharField(choices=[('offer_received', 'Offer received'), ('offer_accepted', 'Offer accepted'), ('offer_rejected', 'Offer rejected'), ('availability_updated', 'Availability updated'), ('message_received', 'Message received'), ('profile_updated', 'Profile updated')], max_length=32)),
                ('summary', models.CharField(max_length=255)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activities',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', '-created_at'], name='activities_user_id_7bdf29_idx')],
            },
        ),
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('soft_hold', 'Soft Hold'), ('booked', 'Booked')], default='available', max_length=16)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(limit_choices_to={'role': 'artist'}, on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'availability_slots',
                'indexes': [models.Index(fields=['user', 'date'], name='availabilit_user_id_0dfed9_idx'), models.Index(fields=['date', 'status'], name='availabilit_date_138123_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_user_date_slot')],
            },
        ),
        migrations.CreateModel(
            name='BookingOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField(blank=True, null=True)),
                ('venue_name', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('amount_cents', models.BigIntegerField(default=0)),
                ('budget_min_cents', models.BigIntegerField(blank=True, null=True)),
                ('budget_max_cents', models.BigIntegerField(blank=True, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=16)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('artist', models.ForeignKey(limit_choices_to={'role': 'artist'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_offers', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'booking_offers',
                'ordering': ('-event_date',),
                'indexes': [models.Index(fields=['artist', 'status', '-event_date'], name='booking_off_artist__42f91f_idx'), models.Index(fields=['requester', '-created_at'], name='booking_off_request_9b7366_idx'), models.Index(fields=['status', 'event_date'], name='booking_off_status_0a3c2b_idx')],
            },
        ),
    ]
