# Generated by Django 5.2.14 on 2026-06-09 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_bookingoffer_seatgeek_performer'),
        ('seatgeek', '0002_event_date_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingoffer',
            name='recipient',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'talent-buyer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookingoffer',
            name='artist',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'artist'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bookingoffer',
            name='seatgeek_performer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_offers', to='seatgeek.performers'),
        ),
        migrations.AddIndex(
            model_name='bookingoffer',
            index=models.Index(fields=['recipient', 'status', '-event_date'], name='booking_off_recipie_d46cd5_idx'),
        ),
    ]
