# Generated by Django 5.1.15 on 2026-08-29 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_bookingoffer_recipient_alter_bookingoffer_artist_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bookingoffer',
            name='booking_offer_artist_xor_seatgeek',
        ),
        migrations.RemoveIndex(
            model_name='bookingoffer',
            name='booking_off_artist__42f91f_idx',
        ),
        migrations.RemoveIndex(
            model_name='bookingoffer',
            name='booking_off_seatgee_6163a6_idx',
        ),
        migrations.RemoveIndex(
            model_name='bookingoffer',
            name='booking_off_recipie_d46cd5_idx',
        ),
        migrations.RemoveField(
            model_name='bookingoffer',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='bookingoffer',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='bookingoffer',
            name='seatgeek_performer',
        ),
        migrations.AddField(
            model_name='bookingoffer',
            name='target_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='bookingoffer',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bookingoffer',
            index=models.Index(fields=['target_user', 'status', '-event_date'], name='booking_off_target__13d0ad_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookingoffer',
            constraint=models.CheckConstraint(condition=models.Q(('target_user__isnull', False), models.Q(('target_email', ''), _negated=True), _connector='OR'), name='booking_offer_has_target'),
        ),
    ]
