# Generated by Django 5.1.15 on 2026-05-06 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'genres',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ArtistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bio', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='artists/covers/')),
                ('experience_years', models.PositiveSmallIntegerField(default=0)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('base_price_cents', models.BigIntegerField(default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'artist'}, on_delete=django.db.models.deletion.CASCADE, related_name='artist_profile', to=settings.AUTH_USER_MODEL)),
                ('genres', models.ManyToManyField(blank=True, related_name='artists', to='catalog.genre')),
            ],
            options={
                'db_table': 'artist_profiles',
            },
        ),
        migrations.CreateModel(
            name='RecentSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('radius_miles', models.PositiveIntegerField(blank=True, null=True)),
                ('genres', models.JSONField(blank=True, default=list)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recent_searches',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='VenueProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='venues/covers/')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'venue'}, on_delete=django.db.models.deletion.CASCADE, related_name='venue_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'venue_profiles',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='catalog.artistprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favorites',
                'indexes': [models.Index(fields=['user', '-created_at'], name='favorites_user_id_f73cef_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'artist'), name='unique_user_artist_favorite')],
            },
        ),
        migrations.AddIndex(
            model_name='artistprofile',
            index=models.Index(fields=['is_published'], name='artist_prof_is_publ_574c5f_idx'),
        ),
        migrations.AddIndex(
            model_name='artistprofile',
            index=models.Index(fields=['latitude', 'longitude'], name='artist_prof_latitud_0fa9ad_idx'),
        ),
        migrations.AddIndex(
            model_name='recentsearch',
            index=models.Index(fields=['user', '-created_at'], name='recent_sear_user_id_5793cc_idx'),
        ),
    ]
