# Generated by Django 5.1.15 on 2026-05-22 05:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('seatgeek', '0002_event_date_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='seatgeek_performer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='seatgeek.performers'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='catalog.artistprofile'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'seatgeek_performer'), name='unique_user_sg_performer_favorite'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('artist__isnull', False), ('seatgeek_performer__isnull', True)), models.Q(('artist__isnull', True), ('seatgeek_performer__isnull', False)), _connector='OR'), name='favorite_artist_xor_seatgeek'),
        ),
    ]
