# Generated by Django 5.1.15 on 2026-07-01 15:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_add_favorite_list'),
        ('seatgeek', '0002_event_date_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_user_artist_favorite',
        ),
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_user_sg_performer_favorite',
        ),
        migrations.RemoveConstraint(
            model_name='favorite',
            name='favorite_artist_xor_seatgeek',
        ),
        migrations.RemoveIndex(
            model_name='favoritelist',
            name='favorite_li_share_t_idx',
        ),
        migrations.AddField(
            model_name='favorite',
            name='seatgeek_venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='seatgeek.venues'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='catalog.venueprofile'),
        ),
        migrations.AlterField(
            model_name='favoritelist',
            name='share_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(condition=models.Q(('artist__isnull', False)), fields=('user', 'artist'), name='unique_user_artist_favorite'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(condition=models.Q(('seatgeek_performer__isnull', False)), fields=('user', 'seatgeek_performer'), name='unique_user_sg_performer_favorite'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(condition=models.Q(('venue__isnull', False)), fields=('user', 'venue'), name='unique_user_venue_favorite'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(condition=models.Q(('seatgeek_venue__isnull', False)), fields=('user', 'seatgeek_venue'), name='unique_user_sg_venue_favorite'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('artist__isnull', False), ('seatgeek_performer__isnull', True), ('seatgeek_venue__isnull', True), ('venue__isnull', True)), models.Q(('artist__isnull', True), ('seatgeek_performer__isnull', False), ('seatgeek_venue__isnull', True), ('venue__isnull', True)), models.Q(('artist__isnull', True), ('seatgeek_performer__isnull', True), ('seatgeek_venue__isnull', True), ('venue__isnull', False)), models.Q(('artist__isnull', True), ('seatgeek_performer__isnull', True), ('seatgeek_venue__isnull', False), ('venue__isnull', True)), _connector='OR'), name='favorite_exactly_one_target'),
        ),
    ]
