# Generated by Django 5.1.15 on 2026-07-01 15:28
# Manually updated to handle unique UUID population for existing rows.

import uuid
from django.db import migrations, models


def populate_venue_share_tokens(apps, schema_editor):
    FavoriteList = apps.get_model("catalog", "FavoriteList")
    for row in FavoriteList.objects.filter(venue_share_token__isnull=True):
        row.venue_share_token = uuid.uuid4()
        row.save(update_fields=["venue_share_token"])


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_add_venue_favorites'),
    ]

    operations = [
        # Step 1: Add venue_is_shared (safe — boolean with default).
        migrations.AddField(
            model_name='favoritelist',
            name='venue_is_shared',
            field=models.BooleanField(default=False),
        ),
        # Step 2a: Add venue_share_token as nullable + non-unique so existing rows
        # don't all receive the same value and hit the unique constraint.
        migrations.AddField(
            model_name='favoritelist',
            name='venue_share_token',
            field=models.UUIDField(null=True, blank=True),
        ),
        # Step 2b: Populate a distinct UUID for every existing row.
        migrations.RunPython(populate_venue_share_tokens, migrations.RunPython.noop),
        # Step 3: Now that every row has a unique value, add the unique index
        # and make the column NOT NULL.
        migrations.AlterField(
            model_name='favoritelist',
            name='venue_share_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
    ]
