# Generated by Django 5.1.15 on 2026-08-18 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=16)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avail_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'avail_lists',
            },
        ),
        migrations.CreateModel(
            name='AvailEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genre', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avail_entries', to=settings.AUTH_USER_MODEL)),
                ('avail_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='avails.availlist')),
            ],
            options={
                'db_table': 'avail_entries',
            },
        ),
        migrations.CreateModel(
            name='AvailShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shared_email', models.EmailField(blank=True, max_length=254)),
                ('message', models.TextField(blank=True)),
                ('avail_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='avails.availlist')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avail_shares_sent', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avail_shares_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'avail_shares',
            },
        ),
        migrations.CreateModel(
            name='AvailDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='avails.availentry')),
            ],
            options={
                'db_table': 'avail_dates',
                'indexes': [models.Index(fields=['entry', 'date'], name='avail_dates_entry_i_07f05f_idx')],
                'constraints': [models.UniqueConstraint(fields=('entry', 'date'), name='uniq_avail_entry_date')],
            },
        ),
        migrations.AddIndex(
            model_name='availlist',
            index=models.Index(fields=['owner', 'visibility'], name='avail_lists_owner_i_22dde5_idx'),
        ),
        migrations.AddIndex(
            model_name='availlist',
            index=models.Index(fields=['visibility'], name='avail_lists_visibil_9c0f3c_idx'),
        ),
        migrations.AddIndex(
            model_name='availentry',
            index=models.Index(fields=['avail_list', 'position'], name='avail_entri_avail_l_a39def_idx'),
        ),
        migrations.AddConstraint(
            model_name='availentry',
            constraint=models.UniqueConstraint(fields=('avail_list', 'artist'), name='uniq_avail_list_artist'),
        ),
        migrations.AddIndex(
            model_name='availshare',
            index=models.Index(fields=['avail_list'], name='avail_share_avail_l_fd33e8_idx'),
        ),
        migrations.AddIndex(
            model_name='availshare',
            index=models.Index(fields=['shared_with'], name='avail_share_shared__a6a793_idx'),
        ),
        migrations.AddConstraint(
            model_name='availshare',
            constraint=models.UniqueConstraint(condition=models.Q(('shared_with__isnull', False)), fields=('avail_list', 'shared_with'), name='uniq_avail_share_user'),
        ),
    ]
